/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.sinhvien;
import  model.DonDeXuat;
import model.SinhVien;
import java.util.ArrayList;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Le Thi Ngoc
 */
public class DeXuatCaiTien extends javax.swing.JFrame {
    ArrayList<DonDeXuat> dons = new ArrayList<DonDeXuat>();
    private static int nextMaDonTapThe = 1;
    /**
     * Creates new form DeXuatCaiTien
     */
    public DeXuatCaiTien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtkhac = new javax.swing.JTextArea();
        txtMongMuon = new javax.swing.JTextField();
        txtTgian = new javax.swing.JTextField();
        txtGopYGV = new javax.swing.JTextField();
        txtGopYForm = new javax.swing.JTextField();
        btlQuayLai = new javax.swing.JButton();
        btlGuiDeXuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Bạn muốn nhà trường mở thêm lớp học phần nào khác?");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Bạn có góp ý gì cho nhà trường về form đăng ký không?");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Bạn có góp ý gì về phương pháp giảng dạy các lớp học phần không?");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Thời gian học của các lớp học phần được mở có phù hợp với sinh viên không?");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Góp ý khác:");

        txtkhac.setColumns(20);
        txtkhac.setRows(5);
        jScrollPane1.setViewportView(txtkhac);

        txtMongMuon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtTgian.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtGopYGV.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtGopYForm.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btlQuayLai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btlQuayLai.setText("Quay lại");
        btlQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlQuayLaiActionPerformed(evt);
            }
        });

        btlGuiDeXuat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btlGuiDeXuat.setText("Gửi đề xuất");
        btlGuiDeXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlGuiDeXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtGopYForm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                                .addComponent(txtMongMuon, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtGopYGV, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                                .addComponent(txtTgian, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btlQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btlGuiDeXuat)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMongMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(txtGopYForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addComponent(txtGopYGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTgian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btlQuayLai)
                    .addComponent(btlGuiDeXuat))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String sinhMaDonTapThe(){
        String maDon = "DTT" + String.format("%03d", nextMaDonTapThe);
        nextMaDonTapThe++;       
        System.out.println(nextMaDonTapThe);
        return maDon;
    }
    private void btlGuiDeXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlGuiDeXuatActionPerformed
                // TODO add your handling code here:
                DonDeXuat x = new DonDeXuat();
               x.setMaDon(sinhMaDonTapThe());
                x.setCauHoi1(txtMongMuon.getText());
                x.setCauHoi2(txtGopYForm.getText());
                x.setCauHoi3(txtGopYGV.getText());
                x.setCauHoi4(txtTgian.getText());
                x.setGopY(txtkhac.getText());
     
             dons.add(x);

                if(txtMongMuon.getText().isEmpty() || txtGopYForm.getText().isEmpty() || txtGopYGV.getText().isEmpty() || txtTgian.getText().isEmpty() || txtkhac.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Nhập dữ liệu trước khi lưu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
                }              
                // Lưu dữ liệu vào file
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("src\\Data\\DonDexuat.txt", true))) {
//
            writer.write(x.getMaDon() + ",");
            writer.write(x.getCauHoi1() + ",");
            writer.write(x.getCauHoi2() + ",");
            writer.write(x.getCauHoi3() + ",");
            writer.write(x.getCauHoi4() + ",");
            writer.write(x.getGopY());

            writer.newLine();
            writer.flush();
            JOptionPane.showMessageDialog(this, "Dữ liệu đã được lưu vào file thành công!");
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi lưu dữ liệu.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btlGuiDeXuatActionPerformed

    private void btlQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlQuayLaiActionPerformed
        TrangChuSinhVien trangchu = new TrangChuSinhVien();
        trangchu.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btlQuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeXuatCaiTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeXuatCaiTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeXuatCaiTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeXuatCaiTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeXuatCaiTien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlGuiDeXuat;
    private javax.swing.JButton btlQuayLai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtGopYForm;
    private javax.swing.JTextField txtGopYGV;
    private javax.swing.JTextField txtMongMuon;
    private javax.swing.JTextField txtTgian;
    private javax.swing.JTextArea txtkhac;
    // End of variables declaration//GEN-END:variables
}
